### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Anzic23** [iobroker-community-adapters/ioBroker.opentherm#20]
Can I translate the interface into Russian? or make the option change language to English. When installed in a Russian location, it is impossible to understand the values of the options in the adapter settings.
![2019-04-15_10-36-56](https://user-images.githubusercontent.com/37106885/56114761-6f4cff80-5f6a-11e9-95d9-87a828cd1bce.png)

**Comment by DutchmanNL** [comment]
thank you, I just see that only the English part is properly implemented something went wrong with all others sorry for that !

I will update the source during the next days to fix the language part.

**Comment by DutchmanNL** [comment]
Hi @Anzic23, I update the git repo with new translations.
Could you please install a version from git and have a review before I publish it on NPM ?

Thank you !

**Comment by Anzic23** [comment]
can't install
ERROR: host.iobroker2-1 Cannot install https://github.com/iobroker-community-adapters/ioBroker.opentherm/tarball/master: 254
ERROR: process exited with code 25

**Comment by Anzic23** [comment]
installed version 0.2.0 by reference. The problem is still present.
![2019-04-19_14-26-04](https://user-images.githubusercontent.com/37106885/56422310-6718fb00-62af-11e9-8e8e-59c21418a5bb.png)
![2019-04-19_14-25-25](https://user-images.githubusercontent.com/37106885/56422313-6b451880-62af-11e9-97f1-28680b7d6b25.png)

**Comment by DutchmanNL** [comment]
> installed version 0.2.0 by reference. The problem is still present.
> ![2019-04-19_14-26-04](https://user-images.githubusercontent.com/37106885/56422310-6718fb00-62af-11e9-8e8e-59c21418a5bb.png)
> ![2019-04-19_14-25-25](https://user-images.githubusercontent.com/37106885/56422313-6b451880-62af-11e9-97f1-28680b7d6b25.png)

did you execute an upload after installation from gtihub by admin or console ?

**Comment by Anzic23** [comment]
> did you execute an upload after installation from gtihub by admin or console ?
yes. in english it's ok. But in Russian - just like was before.

**Comment by DutchmanNL** [comment]
stupid mistake by me, please checkout 0.2.1

**Comment by Anzic23** [comment]
I'm sorry for the long answer. Now the translation is ok. But i can't change anything. It's ok? Or i miss somthing?

**Comment by DutchmanNL** [comment]
> I'm sorry for the long answer. Now the translation is ok. But i can't change anything. It's ok? Or i miss somthing?

sorry for the late reply :/, changes are coming in a new version of the adapter coming soon
