### ISSUE TITLE
New 0.2.3 Version, to many log data

### ISSUE THREAD

**Issue by svenp** [iobroker-community-adapters/ioBroker.opentherm#42]
Hi, 
since Version 0.2.3 the log will grow up with communication data. 
![opentherm info log](https://user-images.githubusercontent.com/649690/74186098-41981c00-4c4a-11ea-8963-454393721616.png)

my quick and dirty hack 

 // this.log.info(data);

solve the Problem for the moment

`client.on('data', (data) => {
try {
//                                      this.log.info(data);
                                      const read = data.toString();`

Thank you for support/improve the Opentherm Adapter

Sven

**Comment by DutchmanNL** [comment]
0.2.3 is currently in dev state will release the final one in an hour and remove the developer logging.

also implemented some new states for troubleshooting, thank you testing & feedback :)

PS : I would be happy with some help getting the proper state definitions :)

**Comment by DutchmanNL** [comment]
done, commit code improvements handled.

can you please check if all is working ok so far and the logging back to a normal level ?
I will release the version on NPM after successfully testing

**Comment by svenp** [comment]
OK , at the moment,the logging show this

![opentherm0 2 3](https://user-images.githubusercontent.com/649690/74190765-2aa9f780-4c53-11ea-84ed-884c0b8e8baa.png)

No normal state :)

**Comment by DutchmanNL** [comment]
fixed https://github.com/iobroker-community-adapters/ioBroker.opentherm/commit/4cf632dc1a8c91fd875753755a1c759dc26696e2
